- aws/sign.go
- s3/multi.go
- s3/s3.go
> Implement v4 for s3

- exp/ses/delivery_notification.go
- exp/ses/delivery_notification_test.go
- exp/ses/notification_requests_test.go
- exp/ses/ses_integration_test.go
Following this http://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#delivery-object I added json objects to receive SNS notifications of SES delivery
> SNSNotifications support for SES

- aws/sign.go
- s3/s3.go
This commit makes some slight changes to the v4 auth code in the s3 package and
changes some of the signature code in aws.
> Enable v4 auth for signing requests with query parameters

- README.md
- TODO.md
Just a minor update to the doc
> updated readme and docs

- s3/s3.go
Those errors happen for example when the server closes the response
before sending the response.
One additional question is whether we want to filter on the method before retrying, for example based on the HTTP method.
> s3: Retry on url.Error too

- s3/s3.go
> Prevent double slashes in UploadSignedURL

- s3/s3.go
Fixes a couple of typos, updates the comment and the parameter name for UploadSignedURL().
> Fix typos, rename parameter and update comment

- dynamodb/attribute.go
- dynamodb/dynamo_query_builder.go
- dynamodb/query.go
- dynamodb/query_builder.go
- dynamodb/scan.go
gofmt also run as previous pull request did not have that done.
> StartKey is now used rather than trying to map the result back to a Key.

- s3/s3.go
- s3/s3_test.go
allows s3.Put to write objects with Reduced Redundancy Storage
> add StorageClass to s3.Options

- dynamodb/attribute.go
- dynamodb/item.go
an example of list attribute as below:
```json
{
"Test":{
"L":[
{"S":"t1"},
{"S":"t2"}
]
}
}
```
they are all normally update , defining TYPE_LIST , creating a function NewListAttribute , encoding list attribute in func (a *Attribute) SetType()
the original function parseAttributes in dynamodb/item.go is only support msi but []msi like values in "L" in the example above .
This is because element in list attribute do not have Name.
So I split parseAttributes into parseAttributes and parseAttribute.
the function of parseAttributes is compatible with original, only support msi and set Name of Attribute in this function . 
but the function of parseAttribute is parsing all types of attributes without setting Name, which is compatible with type of list.
> support attribute type List. 

- kms/kms.go
- kms/kms_test.go
> Fix name of imported packages

- dynamodb/Makefile
Hi Ali:
please take a look at it, thanks.
Regards,
Nick
> update dynamodb-local location, this version will passed test

- sqs/sqs.go
> Rename QueueFromArn to QueueFromUrl

- s3/s3test/server.go
Hello, for testing purposes added range support to s3test get requests. Please review, thanks.
> s3test: Add support for range header with get request

- sqs/responses_test.go
- sqs/sqs.go
- sqs/sqs_test.go
New to Golang. Please criticize liberally :)
> Added sendBatch with attributes call to sqs

- sqs/sqs.go
Missed this with yesterdays PR.
> Fixing edge case with error handling

- s3/s3test/server.go
It is legal when doing a multipart upload to upload may parts in
parallel. Because of the global mutex on the server, those parallel
cases were not handled correctly. We now check at upload completion
time that all parts in the complete request were uploaded.
> s3test: Support part uploads out of order

- dynamodb/attribute.go
Please refer - https://github.com/AdRoll/goamz/issues/384
> adding NewBoolAttribute()

- dynamodb/query_builder.go
Reference: http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-ConditionalOperator
> add SetConditionalOperator function to set conditional operator when calling AWS Query API 

- s3/s3.go
> Append bucket name to path before signing

- kinesis/kinesis.go
- kinesis/kinesis_test.go
- kinesis/query.go
- kinesis/responses_test.go
- kinesis/types.go
As documented here: http://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html
> Add support for Kinesis PutRecords.

- s3/s3test/server.go
Quit() was previously closing the listener, but not closing connections.
With HTTP persistent connections, that would mean that requests could
be served indefinitely afterwards.
This patch adds a "closed" flag on the server, and actively kills
connections after the server has been quitted.
> s3test: Stop serving requests after Quit is called

- s3/s3t_test.go
- s3/s3test/server.go
A fake clock lets us ensure our headers differ from RFC1123 in the same way that Amazon's headers do, even when the test suite is run on the 10th..31st of the month when the different formats produce identical results.
This also makes it possible to use s3test to test application code that is sensitive to the timestamps returned by S3, without resorting to `time.Sleep()`.
> Add fake clock facility to s3test

- autoscaling/autoscaling.go
- autoscaling/autoscaling_test.go
- s3/multi_test.go
Hi, i'm bug fixed ImageId for test and wrapper erros from aws autoscalle api, and update method UpdateAutoScalingGroup for set 0 MinSize, MaxSize and DesiredCapacity.
> Bug fixed autoscaling update group
