AdRoll/goamz

- ec2/ec2.go
Hello,
When I made #278, I made a typo in ec2.go. It checks the wrong field in options to set `VolumeType`. I finally got around to implement a feature that uses that call.
Cheers
> Fix typo in ec2.CreateVolume

- ec2/ec2.go
Hello,
I was implementing a feature that uses `CreateVolume`, and found that `DescribeVolumes` doesn't work, because the parameter is misspelled (has an extra s at the end). See http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVolumes.html for the reference.
Cheers
> Fix the typo in ec2.DescribeVolumes

- aws/aws.go
Hello,
3rd pull request from implementing the code that uses CreateVolume. This one more of a feature request. When you create a volume, you have to specify the availability zone you want the volume to be in.
Cheers,
> Add aws.AvailabilityZone

- dynamodb/item.go
If an error occurs during GetItem, that error should be returned to the client. In the case where the response was empty, EOF is being returned from the failing JSON parse.
> Return DynamoDB GetItem error instead of JSON parse error

- route53/route53.go
Currently, it is not possible to create an AliasTarget in a Change ResourceRecordSets request. This allows AliasTarget to be placed at the right portion of the request.
> route53: add AliasTarget to Change, allow Value to be empty

- sns/http_notification_test.go
- sns/responses_test.go
- sns/sns_test.go
- sns/structs.go
This is my attempt to implement http://docs.aws.amazon.com/sns/latest/dg/json-formats.html#http-notification-json
How did you guys use the sns library without that? Or did I miss something?
> add sns notification request object

- sns/http_notification_test.go
- sns/sns_test.go
- sns/structs.go
Additional tests and support for Subscribe and Unsubscribe. 
@alimoeeny I was thinking that the `SubscribeURL`, `UnsubscribeURL` fields contain already the callback url to subscribe and unsubscribe. Is it worth adding a method like `func (n* SNSNotification) DoUnsubscribe() error`, or would it be a duplicate of `SNS.Unsubscribe(...)`?
In my code I wrote something like the following which however could be a method of SNSNotification
```
func ConfirmSubscribe(notification SNSNotification, sns SNS) (resp, error) {
resp, err := sns.ConfirmSubscription(notification.TopicArn, notification.Token, "false")
}
```
> Additional tests and Subscribe/Unsubscribe support for SNS json notifications

- s3/s3.go
Signing was broken when pre-signing a URL with credentials using a token (like for example when they come from the instance metadata service on EC2).
> S3: Fix presigning of URLs

- sns/http_notifications.go
- sns/http_notifications_test.go
- sns/sns.go
- sns/sns_test.go
- sns/structs.go
@alimoeeny based on our previous chat I rearranged the SNS code related to http endpoints into separated files. I also added a couple of convenience method to subscribe/unsubscribe following the json message.
> sns http support - minor refactoring and added helper methods

- cloudwatch/cloudwatch.go
- cloudwatch/cloudwatch_test.go
Adding description to test alarm and changing PutMetricAlarm to not exit if description is provided.
> Allowing a Description to be used for PutMetricAlarm method

- cloudwatch/cloudwatch.go
After the last pull request I realized that CloudWatch has separate parameters if to have alarms activated when they enter (or re-enter) the OK state.
> adding ability to set okactions

- aws/regions.go
AWS has just added Kinesis endpoint in region `us-west-1`.
> Add Kinesis endpoint for us-west-1

- aws/aws.go
This fixes #334 
If we see a token is near expiry, we call GetAuth to refresh it, and
blindly overwrite our token without checking for error. If an error
is returned by GetAuth, we're left with the zero value Auth object,
which is empty. This means all future service calls will fail, and
since the token is now the empty string, we won't try to call GetAuth
again.
This change makes it so we only store the result of GetAuth if it
returns successfully. If it fails, we will keep using our existing
credentials, but each subsequent call to Token will try again to fetch
new credentials.
> Fix issue where auth token can become empty

- s3/s3.go
The method `UploadSignedURL` can result in incorrect URLs if the given path has a leading slash. All the other methods for signing URLs can handle leading slashes just fine.
This inconsistent behavior can be annoying at times, and always requires special attention to what path is being passed to this method. I believe this should be handled from within the package itself. 
For example, with the following two lines:
```
data.Bucket.UploadSignedURL(fmt.Sprintf("/programs/%s/stdout.txt", prog.Id.Hex()), "PUT", "text/plain", keep)
data.Bucket.SignedURL(fmt.Sprintf("/programs/%s/stdout.txt", prog.Id.Hex()), keep)
```
The first one signs an URL that looks like "https://arturia.s3.amazonaws.com//programs/54d9cc5c39dae80003000001/stdout.txt" (notice the double slashes), while the second one signs …
> Prevent double slashes in UploadSignedURL

- dynamodb/attribute.go
- dynamodb/dynamodb.go
- dynamodb/item.go
- dynamodb/item_test.go
- dynamodb/query_builder.go
- dynamodb/query_builder_test.go
For https://github.com/AdRoll/goamz/issues/308
This PR provides a UpdateExpressionUpdateAttributes method on Table that will allow us to support arbitrary UpdateExpressions to the underlying UpdateItem API endpoint.
The existing UpdateAttributes method on Table could potentially be modified to support a limited subset of UpdateExpressions, but it can't support semantics like "SET #key1.#key2=:val1" that are permitted by the DynamoDB API. Adding a new method rather than extending the existing interface will allow consuming code to avoid the complexity of writing an UpdateExpression unless it's actually needed to express operations on fields of a map (or multiple operations such as a SET and DELETE in the same call). Examples are provided in the associated test code.
Includes:
- extended …
> Expanded support for map type in DynamoDB

- s3/s3test/server.go
This commit implements multipart commit initialization, upload,
completion and abortion. Missing are listing of parts, and listing of
multipart uploads.
This commit also fixes the PUT call on object so that it returns sets
the ETag properly in the response.
> s3test: Partial multipart upload implementation

- s3/s3test/server.go
Somehow my initial tests missed that case, which is handled for normal PUTs
> s3test: Fix potential nil dereference on multipart complete

- cloudwatch/cloudwatch.go
Do not set Value key in map if StatisticValues are set
See Issue https://github.com/AdRoll/goamz/issues/355
> MetricData Value and StatisticValue cannot be specified both

- exp/sdb/sign.go
When using temporary IAM credentials, the auth.Token() function will update the auth.AccessKey when the credentials have expired. As such, the call to the auth.Token() function should be before, not after the usage of auth.AccessKey.
> Fix SDB request signing on auth expiry

- route53/route53.go
Issue #164 and subsequent commit b3599a4 broke ability to change resource record sets for all non-alias records (which are arguably a more common use case than alias records).
This was due to `omitempty` not working on structs. The simplest way I can think of of fixing this without too much impact to to make AliasTarget into a pointer. A nil pointer is then marshalled and doesn't end up in the resulting XML.
> change AliasTarget into a pointer (restore ability to change non-alias records)

- .travis.yml
- route53/route53_test.go
Added a couple of very basic tests that validate AliasTarget behaviour in respect to the change function added in #366.
> add basic test for AliasTarget behavior

- s3/s3.go
Hello, noticed UploadSignedURL was not taking advantage of the S3 endpoint in the returned URLs. Please review, thanks.
> s3: Use S3 endpoint in UploadSignedURL if it is set.

- kms/kms.go
- kms/kms_test.go
- kms/response_test.go
Because original design only reports simple error, in order to take action on specific error, error message should be more detail
> Revise error message for KMS

- s3/multi.go
- s3/multi_test.go
- s3/responses_test.go
As described in the comments in the code, and in http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html , not checking the error means that you can lose data if the multipart upload fails to complete... The previous tests had comments hinting that the original author knew that, but that behavior was not handled.
> s3: Properly check errors when completing multipart commits

- s3/s3.go
Those kind of errors happen when Dial fails, and Dial errors should be
safe to retry, since no actual API call was done yet.
> s3: Retry on dial errors

- route53/route53.go
This is actually only really needed for requests (Route53 will error if
the xmlns is missing on the toplevel request object), but having it for
responses too doesn't hurt.
> route53: Fix xmlns of request and response XML elements

- exp/mturk/mturk.go
- exp/mturk/mturk_test.go
Basic requests left very little customizing space for users of the library, so I added variadic parameters to all functions so that users could add their own parameters.
Furthermore, I changed the GetAssignmentsForHITResponse.Assignment to ==.Assignments. (singular to plural). Prior to this, the decoder would only be able to decode a single assignment for a given HIT. Now, it will build an array of Assignments.
> Added GetHIT and additional params to all requests

- s3/s3.go
amazon can return 503 to indicate that bandwidth exeeded, so it can be nice to have retry.
Added some other 5xx error which make sense to retry in case of receiving.
> retry request on some 5xx errors

- aws/aws.go
- aws/regions.go
- ec2/ec2.go
- ec2/ec2_test.go
- ec2/ec2t_test.go
- elasticache/elasticache_test.go
This allows specifying a signature version for EC2 authentication.
Some regions e.g. Frankfurt support only signature V4 in EC2 requests. This change is the first step to supporting them there.
> Change EC2Endpoint to a ServiceInfo

- s3/multi.go
- s3/s3.go
This pull request aims to S3 Compatible, associate with pull request docker/distribution#902 
This pull request fix two problem:
- send Relative URI instead of Absolute URI when working with RadosGW  (mentioned by https://github.com/AdRoll/goamz/issues/386 and https://github.com/aws/aws-sdk-go/issues/344 )
- complete upload multiple part add http header content-length when working with RadosGW(needed by RadosGW)
ps : when using "generic" as region name indicate that working with RadosGW
> S3 Compatible:support RadosGW when using goamz in docker registry

- s3/multi_test.go
- s3/s3_test.go
Add some tests for supporting RadosGW  mentioned at https://github.com/AdRoll/goamz/pull/392
check two point:
- send relative URI when the region name is 'generic'
- complete multi part contain 'Content-Length' when the region name is 'generic'
> Add some tests for supporting RadosGW

- s3/s3test/server.go
Timezones seem to confuse the official AWS Go SDK:
parsing time "2015-09-07T16:38:36.260+02:00" as "2006-01-02T15:04:05Z":
cannot parse "+02:00" as "Z"
> s3test: Always return UTC times in bucket listing

- kinesis/kinesis.go
Set the X-Amz-Security-Token header, same as many others:
https://github.com/AdRoll/goamz/search?utf8=%E2%9C%93&q=X-Amz-Security-Token
> Use Temporary Security Credentials

- aws/regions.go
That endpoint is the same functionally as s3.amazonaws.com, but
guarantees read-after-write consistency, as mentioned in
https://forums.aws.amazon.com/ann.jspa?annID=3112 .
> s3: Use the s3-external-1 endpoint for US East

- exp/ses/delivery_notification.go
- exp/ses/delivery_notification_test.go
Fix the type definition of Complaint object in SNS notification according to http://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html.
> ses: Fix type definition of Complaint object in SNS notification

- exp/ses/delivery_notification.go
- exp/ses/delivery_notification_requests_test.go
- exp/ses/delivery_notification_test.go
The event adds support for SNS notifications of received emails.
See http://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-notifications.html
I've decided to extend the already-defined `SNSNotification` structure, since the notification object for received emails seems to have similar structure (shares `notificationType`, `mail`; in addition has `receipt` and optionally `content`).
> ses: support SES notifications for received emails

- exp/ses/responses_test.go
- exp/ses/ses.go
- exp/ses/ses_test.go
See http://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html
Note. I've omitted the `Source` ~~and `Destination`~~ (see [below](https://github.com/AdRoll/goamz/pull/411#issuecomment-159450584)) arguments for two reasons:
- if you build the raw email message, it makes more sense to specify it during the build process and embed it in the raw message itself;
- this puts the responsibility of verifying the sent email message solely on the user; for example, making sure that the total number of recipients is less than 50. If you use lower-level API, make sure you're doing it right.
> ses: Support SendRawEmail operation

- s3/s3.go
- s3/s3_test.go
- s3/s3i_test.go
- s3/s3test/server.go
Adds a PutCopy() to the basic functionality test case, and fixes a couple of bugs needed to make it work.
* s3test was sending an empty response body instead of a CopyObjectResult
* PutCopy was using `url.QueryEscape()` to escape the source parameter, which caused the `/` separator to be incorrectly encoded as `%2F`
> Fix (*Bucket)PutCopy bugs

- s3/s3.go
- s3/s3_test.go
Added support for KMS-SSE. Allows server side encryption at rest using KMS managed key or KMS customer key. 
AWS docs here: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingKMSEncryption.html
> KMS-SSE for s3 puts

- aws/sign.go
- aws/sign_test.go
this fixes V4 signing of URLs with query parameters with an empty value. (from #422)
From the [AWS Documentation](http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html):
> For each parameter, append the URI-encoded parameter name, followed by the character '=' (ASCII code 61), followed by the URI-encoded parameter value. Use an empty string for parameters that have no value.
> fix signing of URLs with query parameters with empty value

- aws/aws.go
Use AWS_DEFAULT_PROFILE as documented, falling back to AWS_PROFILE (used
by other tools), finally falling back to "default" if not provided.
> Uses environment variables for selecting credentials file profile

- s3/s3i_test.go
- s3/s3test/server.go
Makes s3test do what AWS does in this situation, i.e., update LastModified but leave the data intact.
> Fix zeroing existing data when copying an object to itself

- .travis.yml
update `travis.yml` to match Travis docs at https://docs.travis-ci.com/user/languages/go 
also to check if we are ok with the soon to be released: `go 1.8`
> Update .travis.yml to check compatibility with Go 1.8 

- s3/s3.go
- s3/s3aclxml.go
- s3/s3aclxml_test.go
In some cases in https://github.com/allegro/akubra supporting tool we need two methods:
- `GetACL` from bucket and objects
- `GetCannedPolicyByAcl` based on results from `GetACL` method for checking permissions in bucket/object
It's important part to developing our next Open Source solution.
This is my proposal of solution for below functionality and new features in S3 `goamz` package.
Please comment and testing my code.
> Adding S3 API methods GetACL + GetCannedPolicyByAcl for getting ACL from bucket and object
